version: '2'
services: 
  bike-postgres:
    image: "postgres:9.6-alpine"
    container_name: bike-postgres
    volumes:
      - bike-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=scrum
      - POSTGRES_USER=scrum
      - POSTGRES_PASSWORD=scrum
    
  bike-app:
    build:
      context: ./bike
      dockerfile: Dockerfile.spring
    container_name: bike-app

    environment:
      - DB_SERVER=bike-postgres
      - POSTGRES_DB=scrum
      - POSTGRES_USER=scrum
      - POSTGRES_PASSWORD=scrum

    ports:
      - 8080:8080
    links: 
      - bike-postgres

  bike-ui:
    build:
      context: ./bike-ui
      dockerfile: Dockerfile.angular
    container_name: bike-ui
    ports: 
      - 4200:80
    links:
      - bike-app
        

  #Volumes for db data
volumes: 
  bike-data:
